spring:
  application:
    name: demo
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3307/USERDETAIL?createDatabaseIfNotExist=true"
    password: "password"
    username: "root"

flyway:
    url: jdbc:mariadb://localhost:3307/
    schemas: USERDETAIL
    user: "root"
    password: "password"







